[package]
name = "ml-inference-candle"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.14.1"
env_logger = "0.11.5"
log = "0.4.22"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
uuid = "1.11.0"
